name: Workflow for Simple Rest API Solution
on: push
jobs:
  build:
    name: Action 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
      - run: dotnet build --configuration Release
      - run: dotnet test --no-restore --verbosity normal
